task:
  task: classification
  classification_type: multiclass
  metric_average: micro
  losses:
    graph_label: cross_entropy
  label_smoothing: 0.0
  output:
  - graph_label
  supervise_on:
  - graph_label
encoder:
  _target_: proteinworkshop.models.graph_encoders.schnet.SchNetModel
  hidden_channels: 512
  out_dim: 32
  num_layers: 6
  num_filters: 128
  num_gaussians: 50
  cutoff: 10.0
  max_num_neighbors: 32
  readout: add
  dipole: false
  mean: null
  std: null
  atomref: null
decoder:
  graph_label:
    _target_: proteinworkshop.models.decoders.mlp_decoder.MLPDecoder
    hidden_dim:
    - 512
    - 512
    dropout: 0.0
    activations:
    - leaky_relu
    - leaky_relu
    - none
    skip: false
    out_dim: 1195
    input: graph_embedding
    batch_norm: true
    batch_norm_output: false
model/params/total: 3559371
model/params/trainable: 3559371
model/params/non_trainable: 0
dataset:
  datamodule:
    _target_: proteinworkshop.datasets.fold_classification.FoldClassificationDataModule
    path: /mnt/d/598/data/FoldClassification/
    split: fold
    batch_size: 32
    pin_memory: true
    num_workers: 4
    dataset_fraction: 1.0
    shuffle_labels: false
    transforms:
      remove_missing_ca:
        _target_: proteinworkshop.tasks.remove_missing_ca.RemoveMissingCa
        fill_value: 1.0e-05
        ca_idx: 1
    overwrite: false
    in_memory: true
  num_classes: 1195
trainer:
  _target_: lightning.pytorch.trainer.Trainer
  default_root_dir: /mnt/d/598/CS598-GNN-UNet/runs/train/runs/2026-03-29_13-35-13
  min_epochs: 1
  max_epochs: 1
  accelerator: gpu
  check_val_every_n_epoch: 1
  deterministic: false
  num_sanity_val_steps: 2
  devices: 1
callbacks:
  model_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: /mnt/d/598/CS598-GNN-UNet/runs/train/runs/2026-03-29_13-35-13/checkpoints
    filename: epoch_{epoch:03d}
    monitor: val/graph_label/accuracy
    verbose: true
    save_last: true
    save_top_k: 5
    mode: max
    auto_insert_metric_name: false
    save_weights_only: false
    every_n_train_steps: null
    train_time_interval: null
    every_n_epochs: 1
    save_on_train_epoch_end: null
  early_stopping:
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: val/graph_label/accuracy
    min_delta: 0.0
    patience: 10
    verbose: true
    mode: max
    strict: true
    check_finite: true
    stopping_threshold: null
    divergence_threshold: null
    check_on_train_epoch_end: false
  model_summary:
    _target_: lightning.pytorch.callbacks.RichModelSummary
    max_depth: -1
  rich_progress_bar:
    _target_: lightning.pytorch.callbacks.RichProgressBar
  learning_rate_monitor:
    _target_: lightning.pytorch.callbacks.LearningRateMonitor
  stop_on_nan:
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: train/loss/total
    min_delta: 0.0
    patience: 10000000
    verbose: true
    mode: min
    strict: true
    check_finite: true
    stopping_threshold: null
    divergence_threshold: null
    check_on_train_epoch_end: null
extras:
  ignore_warnings: true
  enforce_tags: false
  print_config: true
task_name: train
tags: null
ckpt_path: null
seed: 52
cfg:
  env:
    paths:
      root_dir: /mnt/d/598/CS598-GNN-UNet
      data: /mnt/d/598/data
      output_dir: /mnt/d/598/CS598-GNN-UNet/runs/train/runs/2026-03-29_13-35-13
      work_dir: /home/aoj/CS598-GNN-UNet
      log_dir: /mnt/d/598/CS598-GNN-UNet/runs
      runs: /mnt/d/598/CS598-GNN-UNet/runs
      run_dir: /mnt/d/598/CS598-GNN-UNet/runs//26-03-29_13:35:13
    python:
      version: 3.11.11
    init_time: 26-03-29_13:35:13
  dataset:
    datamodule:
      _target_: proteinworkshop.datasets.fold_classification.FoldClassificationDataModule
      path: /mnt/d/598/data/FoldClassification/
      split: fold
      batch_size: 32
      pin_memory: true
      num_workers: 4
      dataset_fraction: 1.0
      shuffle_labels: false
      transforms:
        remove_missing_ca:
          _target_: proteinworkshop.tasks.remove_missing_ca.RemoveMissingCa
          fill_value: 1.0e-05
          ca_idx: 1
      overwrite: false
      in_memory: true
    num_classes: 1195
  features:
    _target_: proteinworkshop.features.factory.ProteinFeaturiser
    representation: CA
    scalar_node_features:
    - amino_acid_one_hot
    - dihedrals
    - sidechain_torsions
    - alpha
    - kappa
    vector_node_features:
    - orientation
    edge_types:
    - knn_16
    scalar_edge_features:
    - edge_distance
    - edge_type
    - node_features
    - sequence_distance
    vector_edge_features:
    - edge_vectors
  encoder:
    _target_: proteinworkshop.models.graph_encoders.schnet.SchNetModel
    hidden_channels: 512
    out_dim: 32
    num_layers: 6
    num_filters: 128
    num_gaussians: 50
    cutoff: 10.0
    max_num_neighbors: 32
    readout: add
    dipole: false
    mean: null
    std: null
    atomref: null
  decoder:
    graph_label:
      _target_: proteinworkshop.models.decoders.mlp_decoder.MLPDecoder
      hidden_dim:
      - 512
      - 512
      dropout: 0.0
      activations:
      - leaky_relu
      - leaky_relu
      - none
      skip: false
      out_dim: 1195
      input: graph_embedding
      batch_norm: true
      batch_norm_output: false
  transforms:
    remove_missing_ca:
      _target_: proteinworkshop.tasks.remove_missing_ca.RemoveMissingCa
      fill_value: 1.0e-05
      ca_idx: 1
  callbacks:
    model_checkpoint:
      _target_: lightning.pytorch.callbacks.ModelCheckpoint
      dirpath: /mnt/d/598/CS598-GNN-UNet/runs/train/runs/2026-03-29_13-35-13/checkpoints
      filename: epoch_{epoch:03d}
      monitor: val/graph_label/accuracy
      verbose: true
      save_last: true
      save_top_k: 5
      mode: max
      auto_insert_metric_name: false
      save_weights_only: false
      every_n_train_steps: null
      train_time_interval: null
      every_n_epochs: 1
      save_on_train_epoch_end: null
    early_stopping:
      _target_: lightning.pytorch.callbacks.EarlyStopping
      monitor: val/graph_label/accuracy
      min_delta: 0.0
      patience: 10
      verbose: true
      mode: max
      strict: true
      check_finite: true
      stopping_threshold: null
      divergence_threshold: null
      check_on_train_epoch_end: false
    model_summary:
      _target_: lightning.pytorch.callbacks.RichModelSummary
      max_depth: -1
    rich_progress_bar:
      _target_: lightning.pytorch.callbacks.RichProgressBar
    learning_rate_monitor:
      _target_: lightning.pytorch.callbacks.LearningRateMonitor
    stop_on_nan:
      _target_: lightning.pytorch.callbacks.EarlyStopping
      monitor: train/loss/total
      min_delta: 0.0
      patience: 10000000
      verbose: true
      mode: min
      strict: true
      check_finite: true
      stopping_threshold: null
      divergence_threshold: null
      check_on_train_epoch_end: null
  optimiser:
    optimizer:
      _target_: torch.optim.Adam
      _partial_: true
      lr: 0.0001
      weight_decay: 0.0
  scheduler: {}
  trainer:
    _target_: lightning.pytorch.trainer.Trainer
    default_root_dir: /mnt/d/598/CS598-GNN-UNet/runs/train/runs/2026-03-29_13-35-13
    min_epochs: 1
    max_epochs: 1
    accelerator: gpu
    check_val_every_n_epoch: 1
    deterministic: false
    num_sanity_val_steps: 2
    devices: 1
  extras:
    ignore_warnings: true
    enforce_tags: false
    print_config: true
  metrics:
    accuracy:
      _target_: torchmetrics.Accuracy
      task: multiclass
      average: micro
      num_classes: 1195
      top_k: 1
    f1_score:
      _target_: torchmetrics.F1Score
      average: macro
      num_classes: 1195
      task: multiclass
    f1_max:
      _target_: proteinworkshop.metrics.f1_max.F1Max
      num_classes: 1195
  task:
    task: classification
    classification_type: multiclass
    metric_average: micro
    losses:
      graph_label: cross_entropy
    label_smoothing: 0.0
    output:
    - graph_label
    supervise_on:
    - graph_label
  logger:
    csv:
      _target_: lightning.pytorch.loggers.csv_logs.CSVLogger
      save_dir: /mnt/d/598/CS598-GNN-UNet/runs/train/runs/2026-03-29_13-35-13
      name: csv/
      prefix: ''
  name: ''
  seed: 52
  num_workers: 10
  task_name: train
  test: true
