wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.11
    cli_version: 0.15.12
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1774488468.732135
    t:
      1:
      - 1
      - 5
      - 9
      - 50
      - 53
      - 55
      - 77
      - 103
      2:
      - 1
      - 5
      - 9
      - 50
      - 53
      - 55
      - 77
      - 103
      3:
      - 7
      - 13
      - 23
      4: 3.11.11
      5: 0.15.12
      8:
      - 8
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: learning_rate
      5: 1
      6:
      - 1
    - 1: train/logit/node_embedding_avgmag
      5: 1
      6:
      - 1
    - 1: train/logit/node_embedding_avg
      5: 1
      6:
      - 1
    - 1: train/logit/node_embedding_std
      5: 1
      6:
      - 1
    - 1: train/logit/graph_embedding_avgmag
      5: 1
      6:
      - 1
    - 1: train/logit/graph_embedding_avg
      5: 1
      6:
      - 1
    - 1: train/logit/graph_embedding_std
      5: 1
      6:
      - 1
    - 1: train/logit/graph_label_avgmag
      5: 1
      6:
      - 1
    - 1: train/logit/graph_label_avg
      5: 1
      6:
      - 1
    - 1: train/logit/graph_label_std
      5: 1
      6:
      - 1
    - 1: train/loss/graph_label
      5: 1
      6:
      - 1
    - 1: train/loss/total
      5: 1
      6:
      - 1
    - 1: train/graph_label/accuracy
      5: 1
      6:
      - 1
    - 1: train/graph_label/f1_score
      5: 1
      6:
      - 1
    - 1: train/graph_label/f1_max
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val/logit/node_embedding_avgmag
      5: 1
      6:
      - 1
    - 1: val/logit/node_embedding_avg
      5: 1
      6:
      - 1
    - 1: val/logit/node_embedding_std
      5: 1
      6:
      - 1
    - 1: val/logit/graph_embedding_avgmag
      5: 1
      6:
      - 1
    - 1: val/logit/graph_embedding_avg
      5: 1
      6:
      - 1
    - 1: val/logit/graph_embedding_std
      5: 1
      6:
      - 1
    - 1: val/logit/graph_label_avgmag
      5: 1
      6:
      - 1
    - 1: val/logit/graph_label_avg
      5: 1
      6:
      - 1
    - 1: val/logit/graph_label_std
      5: 1
      6:
      - 1
    - 1: val/loss/graph_label
      5: 1
      6:
      - 1
    - 1: val/loss/total
      5: 1
      6:
      - 1
    - 1: val/graph_label/accuracy
      5: 1
      6:
      - 1
    - 1: val/graph_label/f1_score
      5: 1
      6:
      - 1
    - 1: val/graph_label/f1_max
      5: 1
      6:
      - 1
    - 1: test/logit/node_embedding_avgmag/fold
      5: 1
      6:
      - 1
    - 1: test/logit/node_embedding_avg/fold
      5: 1
      6:
      - 1
    - 1: test/logit/node_embedding_std/fold
      5: 1
      6:
      - 1
    - 1: test/logit/graph_embedding_avgmag/fold
      5: 1
      6:
      - 1
    - 1: test/logit/graph_embedding_avg/fold
      5: 1
      6:
      - 1
    - 1: test/logit/graph_embedding_std/fold
      5: 1
      6:
      - 1
    - 1: test/logit/graph_label_avgmag/fold
      5: 1
      6:
      - 1
    - 1: test/logit/graph_label_avg/fold
      5: 1
      6:
      - 1
    - 1: test/logit/graph_label_std/fold
      5: 1
      6:
      - 1
    - 1: test/loss/graph_label/fold
      5: 1
      6:
      - 1
    - 1: test/loss/total/fold
      5: 1
      6:
      - 1
    - 1: test/graph_label/accuracy/fold
      5: 1
      6:
      - 1
    - 1: test/graph_label/f1_score/fold
      5: 1
      6:
      - 1
    - 1: test/graph_label/f1_max/fold
      5: 1
      6:
      - 1
    - 1: test/logit/node_embedding_avgmag/family
      5: 1
      6:
      - 1
    - 1: test/logit/node_embedding_avg/family
      5: 1
      6:
      - 1
    - 1: test/logit/node_embedding_std/family
      5: 1
      6:
      - 1
    - 1: test/logit/graph_embedding_avgmag/family
      5: 1
      6:
      - 1
    - 1: test/logit/graph_embedding_avg/family
      5: 1
      6:
      - 1
    - 1: test/logit/graph_embedding_std/family
      5: 1
      6:
      - 1
    - 1: test/logit/graph_label_avgmag/family
      5: 1
      6:
      - 1
    - 1: test/logit/graph_label_avg/family
      5: 1
      6:
      - 1
    - 1: test/logit/graph_label_std/family
      5: 1
      6:
      - 1
    - 1: test/loss/graph_label/family
      5: 1
      6:
      - 1
    - 1: test/loss/total/family
      5: 1
      6:
      - 1
    - 1: test/graph_label/accuracy/family
      5: 1
      6:
      - 1
    - 1: test/graph_label/f1_score/family
      5: 1
      6:
      - 1
    - 1: test/graph_label/f1_max/family
      5: 1
      6:
      - 1
    - 1: test/logit/node_embedding_avgmag/superfamily
      5: 1
      6:
      - 1
    - 1: test/logit/node_embedding_avg/superfamily
      5: 1
      6:
      - 1
    - 1: test/logit/node_embedding_std/superfamily
      5: 1
      6:
      - 1
    - 1: test/logit/graph_embedding_avgmag/superfamily
      5: 1
      6:
      - 1
    - 1: test/logit/graph_embedding_avg/superfamily
      5: 1
      6:
      - 1
    - 1: test/logit/graph_embedding_std/superfamily
      5: 1
      6:
      - 1
    - 1: test/logit/graph_label_avgmag/superfamily
      5: 1
      6:
      - 1
    - 1: test/logit/graph_label_avg/superfamily
      5: 1
      6:
      - 1
    - 1: test/logit/graph_label_std/superfamily
      5: 1
      6:
      - 1
    - 1: test/loss/graph_label/superfamily
      5: 1
      6:
      - 1
    - 1: test/loss/total/superfamily
      5: 1
      6:
      - 1
    - 1: test/graph_label/accuracy/superfamily
      5: 1
      6:
      - 1
    - 1: test/graph_label/f1_score/superfamily
      5: 1
      6:
      - 1
    - 1: test/graph_label/f1_max/superfamily
      5: 1
      6:
      - 1
task:
  desc: null
  value: '{''task'': ''classification'', ''classification_type'': ''multiclass'',
    ''metric_average'': ''micro'', ''losses'': {''graph_label'': ''cross_entropy''},
    ''label_smoothing'': 0.0, ''output'': [''graph_label''], ''supervise_on'': [''graph_label'']}'
encoder:
  desc: null
  value: '{''_target_'': ''proteinworkshop.models.graph_encoders.gvp.GVPGNNModel'',
    ''s_dim'': 128, ''v_dim'': 16, ''s_dim_edge'': 32, ''v_dim_edge'': 1, ''r_max'':
    10.0, ''num_bessel'': 8, ''num_polynomial_cutoff'': 8, ''num_layers'': 5, ''pool'':
    ''sum'', ''residual'': True}'
decoder:
  desc: null
  value: '{''graph_label'': {''_target_'': ''proteinworkshop.models.decoders.mlp_decoder.MLPDecoder'',
    ''hidden_dim'': [512, 512], ''dropout'': 0.0, ''activations'': [''leaky_relu'',
    ''leaky_relu'', ''none''], ''skip'': False, ''out_dim'': ''${dataset.num_classes}'',
    ''input'': ''graph_embedding'', ''batch_norm'': True, ''batch_norm_output'': False}}'
model/params/total:
  desc: null
  value: 2292499
model/params/trainable:
  desc: null
  value: 2292499
model/params/non_trainable:
  desc: null
  value: 0
dataset:
  desc: null
  value: '{''datamodule'': {''_target_'': ''proteinworkshop.datasets.fold_classification.FoldClassificationDataModule'',
    ''path'': ''${env.paths.data}/FoldClassification/'', ''split'': ''fold'', ''batch_size'':
    32, ''pin_memory'': True, ''num_workers'': 0, ''dataset_fraction'': 1.0, ''shuffle_labels'':
    False, ''transforms'': ''${transforms}'', ''overwrite'': False, ''in_memory'':
    True}, ''num_classes'': 1195}'
trainer:
  desc: null
  value: '{''_target_'': ''lightning.pytorch.trainer.Trainer'', ''default_root_dir'':
    ''${env.paths.output_dir}'', ''min_epochs'': 1, ''max_epochs'': 70, ''accelerator'':
    ''gpu'', ''check_val_every_n_epoch'': 1, ''deterministic'': False, ''num_sanity_val_steps'':
    2, ''devices'': 1}'
callbacks:
  desc: null
  value: '{''model_checkpoint'': {''_target_'': ''lightning.pytorch.callbacks.ModelCheckpoint'',
    ''dirpath'': ''${env.paths.output_dir}/checkpoints'', ''filename'': ''epoch_{epoch:03d}'',
    ''monitor'': ''val/graph_label/accuracy'', ''verbose'': True, ''save_last'': True,
    ''save_top_k'': 5, ''mode'': ''max'', ''auto_insert_metric_name'': False, ''save_weights_only'':
    False, ''every_n_train_steps'': None, ''train_time_interval'': None, ''every_n_epochs'':
    1, ''save_on_train_epoch_end'': None}, ''early_stopping'': {''_target_'': ''lightning.pytorch.callbacks.EarlyStopping'',
    ''monitor'': ''val/graph_label/accuracy'', ''min_delta'': 0.0, ''patience'': 10,
    ''verbose'': True, ''mode'': ''max'', ''strict'': True, ''check_finite'': True,
    ''stopping_threshold'': None, ''divergence_threshold'': None, ''check_on_train_epoch_end'':
    False}, ''model_summary'': {''_target_'': ''lightning.pytorch.callbacks.RichModelSummary'',
    ''max_depth'': -1}, ''rich_progress_bar'': {''_target_'': ''lightning.pytorch.callbacks.RichProgressBar''},
    ''learning_rate_monitor'': {''_target_'': ''lightning.pytorch.callbacks.LearningRateMonitor''},
    ''stop_on_nan'': {''_target_'': ''lightning.pytorch.callbacks.EarlyStopping'',
    ''monitor'': ''train/loss/total'', ''min_delta'': 0.0, ''patience'': 10000000,
    ''verbose'': True, ''mode'': ''min'', ''strict'': True, ''check_finite'': True,
    ''stopping_threshold'': None, ''divergence_threshold'': None, ''check_on_train_epoch_end'':
    None}}'
extras:
  desc: null
  value: '{''ignore_warnings'': True, ''enforce_tags'': False, ''print_config'': True}'
task_name:
  desc: null
  value: train
tags:
  desc: null
  value: null
ckpt_path:
  desc: null
  value: null
seed:
  desc: null
  value: 23371
cfg:
  desc: null
  value: '{''env'': {''paths'': {''root_dir'': ''${oc.env:ROOT_DIR}'', ''data'': ''${oc.env:DATA_PATH}'',
    ''output_dir'': ''${hydra:runtime.output_dir}'', ''work_dir'': ''${hydra:runtime.cwd}'',
    ''log_dir'': ''${oc.env:RUNS_PATH}'', ''runs'': ''${oc.env:RUNS_PATH}'', ''run_dir'':
    ''${env.paths.runs}/${name}/${env.init_time}''}, ''python'': {''version'': ''${python_version:micro}''},
    ''init_time'': ''${now:%y-%m-%d_%H:%M:%S}''}, ''dataset'': {''datamodule'': {''_target_'':
    ''proteinworkshop.datasets.fold_classification.FoldClassificationDataModule'',
    ''path'': ''${env.paths.data}/FoldClassification/'', ''split'': ''fold'', ''batch_size'':
    32, ''pin_memory'': True, ''num_workers'': 0, ''dataset_fraction'': 1.0, ''shuffle_labels'':
    False, ''transforms'': ''${transforms}'', ''overwrite'': False, ''in_memory'':
    True}, ''num_classes'': 1195}, ''features'': {''_target_'': ''proteinworkshop.features.factory.ProteinFeaturiser'',
    ''representation'': ''CA'', ''scalar_node_features'': [''amino_acid_one_hot'',
    ''dihedrals'', ''sidechain_torsions'', ''alpha'', ''kappa''], ''vector_node_features'':
    [''orientation''], ''edge_types'': [''knn_16''], ''scalar_edge_features'': [''edge_distance'',
    ''edge_type'', ''node_features'', ''sequence_distance''], ''vector_edge_features'':
    [''edge_vectors'']}, ''encoder'': {''_target_'': ''proteinworkshop.models.graph_encoders.gvp.GVPGNNModel'',
    ''s_dim'': 128, ''v_dim'': 16, ''s_dim_edge'': 32, ''v_dim_edge'': 1, ''r_max'':
    10.0, ''num_bessel'': 8, ''num_polynomial_cutoff'': 8, ''num_layers'': 5, ''pool'':
    ''sum'', ''residual'': True}, ''decoder'': {''graph_label'': {''_target_'': ''proteinworkshop.models.decoders.mlp_decoder.MLPDecoder'',
    ''hidden_dim'': [512, 512], ''dropout'': 0.0, ''activations'': [''leaky_relu'',
    ''leaky_relu'', ''none''], ''skip'': False, ''out_dim'': ''${dataset.num_classes}'',
    ''input'': ''graph_embedding'', ''batch_norm'': True, ''batch_norm_output'': False}},
    ''transforms'': {''remove_missing_ca'': {''_target_'': ''proteinworkshop.tasks.remove_missing_ca.RemoveMissingCa'',
    ''fill_value'': 1e-05, ''ca_idx'': 1}}, ''callbacks'': {''model_checkpoint'':
    {''_target_'': ''lightning.pytorch.callbacks.ModelCheckpoint'', ''dirpath'': ''${env.paths.output_dir}/checkpoints'',
    ''filename'': ''epoch_{epoch:03d}'', ''monitor'': ''val/graph_label/accuracy'',
    ''verbose'': True, ''save_last'': True, ''save_top_k'': 5, ''mode'': ''max'',
    ''auto_insert_metric_name'': False, ''save_weights_only'': False, ''every_n_train_steps'':
    None, ''train_time_interval'': None, ''every_n_epochs'': 1, ''save_on_train_epoch_end'':
    None}, ''early_stopping'': {''_target_'': ''lightning.pytorch.callbacks.EarlyStopping'',
    ''monitor'': ''val/graph_label/accuracy'', ''min_delta'': 0.0, ''patience'': 10,
    ''verbose'': True, ''mode'': ''max'', ''strict'': True, ''check_finite'': True,
    ''stopping_threshold'': None, ''divergence_threshold'': None, ''check_on_train_epoch_end'':
    False}, ''model_summary'': {''_target_'': ''lightning.pytorch.callbacks.RichModelSummary'',
    ''max_depth'': -1}, ''rich_progress_bar'': {''_target_'': ''lightning.pytorch.callbacks.RichProgressBar''},
    ''learning_rate_monitor'': {''_target_'': ''lightning.pytorch.callbacks.LearningRateMonitor''},
    ''stop_on_nan'': {''_target_'': ''lightning.pytorch.callbacks.EarlyStopping'',
    ''monitor'': ''train/loss/total'', ''min_delta'': 0.0, ''patience'': 10000000,
    ''verbose'': True, ''mode'': ''min'', ''strict'': True, ''check_finite'': True,
    ''stopping_threshold'': None, ''divergence_threshold'': None, ''check_on_train_epoch_end'':
    None}}, ''optimiser'': {''optimizer'': {''_target_'': ''torch.optim.Adam'', ''_partial_'':
    True, ''lr'': 0.0005, ''weight_decay'': 0.001}}, ''scheduler'': {''scheduler'':
    {''_target_'': ''torch.optim.lr_scheduler.ReduceLROnPlateau'', ''_partial_'':
    True, ''mode'': ''min'', ''factor'': 0.6, ''patience'': 5, ''verbose'': True},
    ''interval'': ''epoch'', ''frequency'': 1, ''monitor'': ''val/loss/total'', ''strict'':
    True, ''name'': ''learning_rate''}, ''trainer'': {''_target_'': ''lightning.pytorch.trainer.Trainer'',
    ''default_root_dir'': ''${env.paths.output_dir}'', ''min_epochs'': 1, ''max_epochs'':
    70, ''accelerator'': ''gpu'', ''check_val_every_n_epoch'': 1, ''deterministic'':
    False, ''num_sanity_val_steps'': 2, ''devices'': 1}, ''extras'': {''ignore_warnings'':
    True, ''enforce_tags'': False, ''print_config'': True}, ''metrics'': {''accuracy'':
    {''_target_'': ''torchmetrics.Accuracy'', ''task'': ''${task.classification_type}'',
    ''average'': ''${task.metric_average}'', ''num_classes'': ''${dataset.num_classes}'',
    ''top_k'': 1}, ''f1_score'': {''_target_'': ''torchmetrics.F1Score'', ''average'':
    ''macro'', ''num_classes'': ''${dataset.num_classes}'', ''task'': ''${task.classification_type}''},
    ''f1_max'': {''_target_'': ''proteinworkshop.metrics.f1_max.F1Max'', ''num_classes'':
    ''${dataset.num_classes}''}}, ''task'': {''task'': ''classification'', ''classification_type'':
    ''multiclass'', ''metric_average'': ''micro'', ''losses'': {''graph_label'': ''cross_entropy''},
    ''label_smoothing'': 0.0, ''output'': [''graph_label''], ''supervise_on'': [''graph_label'']},
    ''logger'': {''wandb'': {''_target_'': ''lightning.pytorch.loggers.wandb.WandbLogger'',
    ''name'': ''${name}'', ''save_dir'': ''${env.paths.output_dir}'', ''offline'':
    False, ''id'': None, ''anonymous'': None, ''entity'': ''${oc.env:WANDB_ENTITY}'',
    ''project'': ''${oc.env:WANDB_PROJECT}'', ''log_model'': False, ''prefix'': '''',
    ''group'': '''', ''tags'': [], ''job_type'': ''''}}, ''name'': ''gvp/fold_fold/0.0005/BN+WD_1e-3+x2'',
    ''seed'': 23371, ''num_workers'': 16, ''task_name'': ''train'', ''test'': True}'
