model_name: UnetHeteroGVPForLBA
s_dim: 128
v_dim: 16
s_dim_edge: 32
v_dim_edge: 1
r_max: 10.0
num_bessel: 8
num_polynomial_cutoff: 5
num_layers: 5
pool: mean
fps_ratio: 0.6
cross_cutoff: 6.0
enc_drop_rate: 0.1
head_hidden_dim: 256
head_drop_rate: 0.1
lr: 0.0005
weight_decay: 0.001
lr_patience: 10
lr_factor: 0.5
lr_min: 1.0e-06
lba_split: 30
batch_size: 8
num_workers: 4
pin_memory: false
data_root: /scratch/ziyiz14/data/GNN_Unet/data
